version: '3.4'

services:
  front:
    build: ./desafio-impulso-dotnet/ClientApp
    container_name: angular_front
    ports:
      - 8080:8080
    links:
      -  back
    depends_on:
      -  back
  back:
    image: ${DOCKER_REGISTRY-}desafioimpulsodotnet
    build: 
      context: .
      dockerfile: desafio-impulso-dotnet/Dockerfile
    container_name: dotnet_back
    ports:
      - 5000:80